### PR TITLE
Removes bitbucket service

### PR DESCRIPTION
**Pull request by sbastn**
Based on #23 and Bitbucket's documentation: https://confluence.atlassian.com/bitbucket/associate-an-existing-domain-with-an-account-221449746.html, this PR removes Bitbucket's one-click services.

### CODE REVIEW

**Comment by weppos** [comment]
As of today, we can't remove a service as our system will break if we do it.

**Comment by sbastn** [comment]
Closed until we add a way to deprecate services

**Comment by weppos** [comment]
@sbastn I left it open, as a reminder for what we have to remove. I also created in the past a `requires-internal-support` label to flag such items.

We need to maintain somewhere a list of services we want to remove. Are you fine to maintain it here?

**Comment by sbastn** [comment]
@weppos I am fine to maintain it here, but with issues. You'll see that we have a couple more dealing with deprecated services. No need for a pending PR if it's doing the wrong thing, IMO.

**Comment by weppos** [comment]
I agree. I did not realize it was a PR.

**Pull request closed without merging**
