### PR TITLE
Add surge.sh

### PR DESCRIPTION
**Pull request by adambrault**
Surge is pretty handy. :)

### CODE REVIEW

**Comment by sbastn** [comment]
Thanks for this PR @adambrault. Sorry it took so long for us to review it. 

We support CNAME-like behavior on apex domains with the ALIAS record: https://support.dnsimple.com/articles/alias-record/ so you can remove the `A` record pointing to `45.55.110.124` and use:

```
  "type": "ALIAS",
  "content": "na-west1.surge.sh",
  "ttl": 3600
```

**Comment by adambrault** [comment]
@sbastn Thanks! Just made that change :)

**Comment by sbastn** [comment]
Thanks @adambrault for making the changes. I ran your configuration through our test environment but it failed because the logo is called "surge.png" and not "logo.png". I'll make sure this is clearer on our README file. If you make that last change, this is good to go and I'll merge it right away.

Thanks again!

**Comment by adambrault** [comment]
@sbastn done! thanks!

**Comment by sbastn** [comment]
Thanks for your contribution @adambrault !

**Pull request merged**
