### PR TITLE
add fanout

### PR DESCRIPTION
**Pull request by jkarneges**
Fanout is a pubsub cloud service. It allows users to setup custom domains that clients connect to.

### CODE REVIEW

**Comment by sbastn** [comment]
Thanks for your contribution @jkarneges. Merging fanout service into master

**Comment by jkarneges** [comment]
@sbastn Thanks for accepting!

I just realized something. In most cases users point a subdomain at Fanout's servers rather than the base domain. Is it possible to allow the user to type in an optional subdomain? I see some services have a "default-subdomain" in their config, but the user does not get a chance to change this value.

**Comment by sbastn** [comment]
@jkarneges we have a way to do this, but it's not yet visible on our UI. We'll be working shortly to add this feature. When it's ready, we can reconfigure this service to prompt for the subdomain.

**Comment by jkarneges** [comment]
Nice, looking forward to it.

**Pull request merged**
